// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress';

export const sidebar: DefaultTheme.SidebarItem[] = [
  {
    text: 'Introduction',
    link: '/'
  },
  {
    text: 'Install',
    link: '/install'
  },
  {
    text: 'Usage',
    link: '/usage'
  },
  {
    text: 'API coverage',
    link: '/api-coverage'
  },
  {
    text: 'Development',
    link: '/development'
  },
  {
    text: 'License',
    link: '/license'
  }
];
